FROM node:24 AS build-stage
WORKDIR /usr/src/app

COPY . .

ENV VITE_BACKEND_URL=/api

RUN npm ci
RUN npm run build

RUN npm run test

FROM nginx:1.29-alpine

COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html
